import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateUserTable1583033145800 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.query(`create table if not exists b_user (
      id int(18) not null auto_increment,
      timestamp_x timestamp not null default current_timestamp on update current_timestamp,
      login varchar(50) not null,
      password varchar(50) not null,
      checkword varchar(50) default null,
      active char(1) not null default 'y',
      name varchar(50) default null,
      last_name varchar(50) default null,
      email varchar(255) not null,
      last_login datetime default null,
      date_register datetime not null,
      lid char(2) default null,
      personal_profession varchar(255) default null,
      personal_www varchar(255) default null,
      personal_icq varchar(255) default null,
      personal_gender char(1) default null,
      personal_birthdate varchar(50) default null,
      personal_photo int(18) default null,
      personal_phone varchar(255) default null,
      personal_fax varchar(255) default null,
      personal_mobile varchar(255) default null,
      personal_pager varchar(255) default null,
      personal_street text,
      personal_mailbox varchar(255) default null,
      personal_city varchar(255) default null,
      personal_state varchar(255) default null,
      personal_zip varchar(255) default null,
      personal_country varchar(255) default null,
      personal_notes text,
      work_company varchar(255) default null,
      work_department varchar(255) default null,
      work_position varchar(255) default null,
      work_www varchar(255) default null,
      work_phone varchar(255) default null,
      work_fax varchar(255) default null,
      work_pager varchar(255) default null,
      work_street text,
      work_mailbox varchar(255) default null,
      work_city varchar(255) default null,
      work_state varchar(255) default null,
      work_zip varchar(255) default null,
      work_country varchar(255) default null,
      work_profile text,
      work_logo int(18) default null,
      work_notes text,
      admin_notes text,
      stored_hash varchar(32) default null,
      xml_id varchar(255) default null,
      personal_birthday date default null,
      external_auth_id varchar(255) default null,
      checkword_time datetime default null,
      second_name varchar(50) default null,
      confirm_code varchar(8) default null,
      login_attempts int(18) default null,
      last_activity_date datetime default null,
      auto_time_zone char(1) default null,
      time_zone varchar(50) default null,
      primary key  (id),
      unique key ix_login (login,external_auth_id),
      key ix_b_user_email (email),
      key ix_b_user_activity_date (last_activity_date),
      key ix_b_user_xml_id (xml_id)
    ) default charset=cp1251 auto_increment=6897 ;`);
  }

  public async down(queryRunner: QueryRunner): Promise<any> {
    await queryRunner.dropTable('b_user');
  }
}
