version: 0.2
 
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecommerce-backend:latest .
      - docker tag ecommerce-backend:latest 664947791947.dkr.ecr.eu-central-1.amazonaws.com/ecommerce-backend:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 664947791947.dkr.ecr.eu-central-1.amazonaws.com/ecommerce-backend:latest
      # docker push 123456789012.dkr.ecr.eu-central-1.amazonaws.com/randserver:0.0.1