version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bitrix
    ports:
      - '5432:5432'
      # CREATE DATABASE bitrix_test