--- 
  jobs: 
    build: 
      docker: 
        - 
          image: "circleci/node:current"
      steps: 
        - checkout
        - 
          run: "echo \"npm installing\""
        - 
          run: "yarn install"
    test: 
      docker: 
        - 
          image: "circleci/node:current"
      steps: 
        - checkout
        - 
          run: "echo \"run testing\""
        - 
          run: "sudo yarn presetup"
        - 
          run: "yarn test"
  version: 2.1
  workflows: 
    build_test_lint: 
      jobs: 
        - build
        - test
    version: 2.1
  