jobs:
  build:
    docker:
      - image: 'circleci/node:current'  
    steps:
      - checkout
      - run: echo "npm installing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn presetup
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker:
          docker_layer_caching: true    
      - run: yarn ci:docker
      - add_ssh_keys:
          fingerprints:
            a8:ad:61:7b:b9:07:03:d1:6e:64:3c:70:47:7f:81:7c
      - run: yarn aws:deploy
  test:
    docker:
      - image: 'circleci/node:current'
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: bitrix_test
    steps:
      - checkout
      - run: echo "run testing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn presetup
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
version: 2.1
workflows:
  build_test_lint:
    jobs:
      - build
      - test
  version: 2.1
