jobs:
  build:
    docker:
      - image: 'circleci/node:current'  
    steps:
      - checkout
      - run: echo "npm installing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn presetup
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker:
          docker_layer_caching: true    
      - run: yarn ci:docker
  test:
    docker:
      - image: 'circleci/node:current'
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: bitrix_test
    steps:
      - checkout
      - run: echo "run testing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn presetup
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.11
workflows:
  build_test_lint:
    jobs:
      # - test
      # - build:
      #     requires:
      #       - test
      - aws-code-deploy/deploy:
          # requires:
          #   - build
          application-name: e-b
          deployment-group: e-b-2021-03
          service-role-arn: arn:aws:iam::664947791947:role/CodeDeployService
          bundle-bucket: sc5a94-deploy-scripts
          bundle-key: ecommerce-backend/sc5a94-deploy-scripts
          bundle-type: zip
  version: 2.1
